In [3]:
#answer 1

import numpy as npy
s = npy.arange(8, 18)
print("Original array:")
print(s)
print("Reverse array:")
s = s[::-1]
print(s)

Original array:
[ 8  9 10 11 12 13 14 15 16 17]
Reverse array:
[17 16 15 14 13 12 11 10  9  8]


In [2]:
#answer 2

import numpy as npy
s = npy.ones((6,6))
print("Original array:")
print(s)
print("1 on the border and 0 inside in the array")
s[1:-1,1:-1] = 0
print(s)

Original array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [5]:
#answer 3

import numpy as npy
array1 = npy.array([8, 10, 18, 23, 31])
print("Array1: ",array1)
array2 = [8, 31]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(npy.in1d(array1, array2))

Array1:  [ 8 10 18 23 31]
Array2:  [8, 31]
Compare each element of array1 and array2
[ True False False False  True]


In [9]:
#answer 4

import numpy as np
array1 = np.array([10, 18, 11, 38, 49, 60])
print("Array1: ",array1)
array2 = [10, 11, 31, 42, 49]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [10 18 11 38 49 60]
Array2:  [10, 11, 31, 42, 49]
Unique values in array1 that are not in array2:
[18 38 60]


In [8]:
#answer 5

import numpy as npy
s =  npy.diagflat([4, 5, 6, 8])
print(s)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
